CREATE TABLE table_m3 (
    satisfaction VARCHAR(50),
    customer_type VARCHAR(50),
    age INTEGER,
    type_of_travel VARCHAR(50),
    class VARCHAR(50),
    flight_distance INTEGER,
    seat_comfort INTEGER,
    departure_arrival_time_convenient INTEGER,
    food_and_drink INTEGER,
    gate_location INTEGER,
    inflight_wifi_service INTEGER,
    inflight_entertainment INTEGER,
    online_support INTEGER,
    ease_of_online_booking INTEGER,
    onboard_service INTEGER,
    leg_room_service INTEGER,
    baggage_handling INTEGER,
    checkin_service INTEGER,
    cleanliness INTEGER,
    online_boarding INTEGER,
    departure_delay_in_minutes INTEGER,
    arrival_delay_in_minutes FLOAT
);